### ISSUE TITLE
Cargo.toml - I am confused

### ISSUE THREAD

**Issue by minecrawler** [gfx-rs/gfx#1206]
When opening Cargo.toml, I see the following

```toml
[package]
name = "gfx_app"
version = "0.4.0"
description = "GFX example application framework"
```

However, GFX should be version 0.14 according to Crates.io and the repository in front of me should be GFX (not an example application). Did I miss anything? Where does the version number come from?
