### ISSUE TITLE
example of gfx-backend-gl v0.4.0 doesn't compile

### ISSUE THREAD

**Issue by SimonWoodburyForget** [gfx-rs/gfx#3129]
Reproduction involves just getting the latest version from crates.io with a `Cargo.toml`, and the crate itself wont compile.

```toml
# ...
[dependencies]
gfx-backend-gl = "*" 
```

More specifically, I was trying to get the example to compile locally, as opposed to building from the example repository itself, and couldn't get it working.

The error:

```
   Compiling gfx-backend-gl v0.4.0
error[E0308]: mismatched types
    --> /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.4.0/src/device.rs:1945:21
     |
1945 |                     config.extent.width as f64,
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found f64

error[E0308]: mismatched types
    --> /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.4.0/src/device.rs:1946:21
     |
1946 |                     config.extent.height as f64,
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found f64

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `gfx-backend-gl`.
```

It looks like the version on https://crates.io/crates/gfx-backend-gl is 3 months old, while the version in the Github master is 11 days old https://github.com/gfx-rs/gfx/tree/master/src/backend/gl

**Comment by kvark** [comment]
What example are you building?
If you just check out the repository and build the examples with GL, does it not work for you? We test that on CI.
If you want to try an example code for the *published* gfx-rs version, you need to see one in the [hal-0.4 branch](https://github.com/gfx-rs/gfx/tree/hal-0.4/examples) instead.

**Comment by SimonWoodburyForget** [comment]
The latest published `gfx-backend-gl` crate doesn't compile at all. I can't get an empty application to compile. -- For example, in a new project `Cargo.toml`:

```toml
# ...
[features]
default = []
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl", "gfx-backend-gl/glutin"]
wgl = ["gfx-backend-gl", "gfx-backend-gl/wgl"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]
unstable = []

[dependencies]
image = "0.21"
log = "0.4"
hal = { version = "0.4", package = "gfx-hal" }
gfx-backend-empty = { version = "0.4" }
winit = { version = "0.20", features = ["web-sys"] }

[target.'cfg(debug_assertions)'.dependencies]
env_logger = "0.6"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glsl-to-spirv = "0.1.4"

[dependencies.gfx-backend-gl]
version = "0.4"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.51"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.6"
features = [ "console", "Document", "Element", "HtmlElement", "Node", "Window" ]

[dependencies.gfx-backend-vulkan]
version = "0.4"
features = ["x11"]
optional = true

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies.gfx-backend-metal]
version = "0.4"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx11]
version = "0.4"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.4"
optional = true
```

(it's just the example with paths removed) and then:

```bash
cargo build --features=gl
```
..would return the error above.
