### ISSUE TITLE
UnsupportedWindowHandle - Error when creating the surface

### ISSUE THREAD

**Issue by ab0v3g4me** [gfx-rs/gfx#3163]
Well this is my snippet code that when run panics:
```rust
        let event_loop = EventLoop::new();
        
        let wb = winit::window::WindowBuilder::new()
        .with_min_inner_size(winit::dpi::Size::Logical(winit::dpi::LogicalSize::new(
            64.0, 64.0,
        )))
        .with_inner_size(winit::dpi::Size::Physical(winit::dpi::PhysicalSize::new(
            Self::DEFAULT_WIDTH,
            Self::DEFAULT_HEIGHT,
        )))
        .with_title("Island Defense 2".to_string());

        let window = wb.build(&event_loop).unwrap();

        let instance =  backend::Instance::create("Island Defense 2", 1).expect("Unsupported backend.");
        let mut surface = unsafe { instance.create_surface(&window).unwrap() }; 
```
Yet the `quad` example does compile and works perfectly, so what's going on here ?

Here's the Cargo.toml in case it's the cause:
```toml
[package]
name = "island-defense-2"
version = "0.1.0"
edition = "2018"

[features]
default = ["vulkan"]
metal = ["gfx-backend-metal"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
winit = "0.22.0"
lazy_static = "1.4.0"
gfx-hal = { git = "https://github.com/gfx-rs/gfx", version = "0.4.1" }

[target.'cfg(not(target_os = "macos"))'.dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
version = "0.4.0"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
git = "https://github.com/gfx-rs/gfx"
version = "0.4.3"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
git = "https://github.com/gfx-rs/gfx"
version = "0.4.0"
optional = true
```
