### ISSUE TITLE
error: can't find crate for `gfx`

### ISSUE THREAD

**Issue by endel** [gfx-rs/gfx#792]
Hello there,

I'm new to rust and `gfx`. I'm trying to build one of the examples as an standalone project with `gfx` dependency, but no success yet.

Output error:

```
$ cargo run
   Compiling rust-em-all v0.0.1 (file:///Users/endel/Projects/rust-em-all)
   Compiling glfw-sys v3.1.2
   Compiling rustc-serialize v0.3.15
   Compiling advapi32-sys v0.1.2
src/main.rs:17:1: 17:18 error: can't find crate for `gfx`
src/main.rs:17 extern crate gfx;
               ^~~~~~~~~~~~~~~~~
error: aborting due to previous error
   Compiling draw_state v0.1.2
   Compiling xml-rs v0.1.25
   Compiling malloc_buf v0.0.5
   Compiling log v0.3.1
   Compiling gl_common v0.0.4
   Compiling core-foundation v0.1.0
   Compiling shared_library v0.1.0
```

Here is my `Cargo.toml` file:

```toml
[package]
name = "rust-em-all"
version = "0.0.1"
authors = ["Endel Dreyer <endel.dreyer@gmail.com>"]
build = "src/main.rs"

[dependencies]
gfx = "0.6"
gfx_device_gl = "0.4"
gfx_window_glutin = "0.3"
gfx_window_glfw = "0.2"
```

My `src/main.rs` file is the same as [examples/performance/main.rs](https://github.com/gfx-rs/gfx/blob/master/examples/performance/main.rs)

What should I do?
